version: '3.8'

services:
  spring-app:
    build: .
    container_name: spring-app
    environment:
      DB_USER: springapp
      DB_PASSWORD: XjbcyZPHwD
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
      - kafka

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: XjbcyZPHwD
    ports:
      - "1521:1521"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
